import { Router } from "express";
import itemRouter from "./item.routes.js";
import trashRouter from "./trash.routes.js";
import authRouter from "./auth.routes.js";
import adminUserRouter from "./admin-user.routes.js";
import shareRouter from "./share.routes.js";
import uploadRouter from "./upload.routes.js";
import storageRouter from "./storage.routes.js";
import googleDriveRouter from "./google-drive.routes.js";
import searchRouter from "./search.routes.js";
import billingRouter from "./billing.routes.js";

const apiRouter = Router();
apiRouter.use("/items", itemRouter);
apiRouter.use("/trash", trashRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/admin/users", adminUserRouter);
apiRouter.use("/shares", shareRouter);
apiRouter.use("/uploads", uploadRouter);
apiRouter.use("/storage", storageRouter);
apiRouter.use("/imports/google-drive", googleDriveRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/billing", billingRouter);
export default apiRouter;
