import { Router } from "express";
import itemRouter from "./item.routes.js";
import trashRouter from "./trash.routes.js";
import authRouter from "./auth.routes.js";
import adminUserRouter from "./admin-user.routes.js";
import shareRouter from "./share.routes.js";
import uploadRouter from "./upload.routes.js";
const apiRouter = Router();
apiRouter.use("/items", itemRouter);
apiRouter.use("/trash", trashRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/admin/users", adminUserRouter);
apiRouter.use("/shares", shareRouter);
apiRouter.use("/uploads", uploadRouter);
export default apiRouter;
