import { PolicyPage, PolicySection, SupportLink } from "@/components/legal/policy-page";
export const metadata = { title: "Privacy Policy", description: "How DataDock handles personal data." };
export default function Page() { return <PolicyPage eyebrow="Legal" title="Privacy Policy" description="What DataDock collects, why it is used, and the choices available to you.">
  <PolicySection title="Operator and contact"><p>DataDock is operated by Rajat Pandey, an individual developer based in India. Privacy requests can be sent to <SupportLink />.</p></PolicySection>
  <PolicySection title="Information we collect"><ul><li>Account details including name, email, encrypted password credentials, role, and verification status.</li><li>Files, folders, metadata, sharing settings, and storage usage.</li><li>Expiring session and security information.</li><li>Razorpay subscription identifiers, plan, status, and billing dates. We do not store complete payment credentials.</li><li>Technical logs that may include IP address, browser details, request paths, timestamps, and errors.</li></ul></PolicySection>
  <PolicySection title="How we use it"><p>We use information to provide storage and sharing, authenticate accounts, enforce quotas, process subscriptions, prevent abuse, diagnose failures, and send service or security messages.</p></PolicySection>
  <PolicySection title="Service providers"><p>DataDock uses MongoDB Atlas, Amazon S3, Redis, Razorpay, Resend, and Google services where necessary to operate the features you choose. Each provider is governed by its own terms.</p></PolicySection>
  <PolicySection title="Google Drive"><p>Drive import requests read-only access with your consent. Connection credentials are encrypted at rest and used only to show and import files you select. Access can be revoked in your Google Account.</p></PolicySection>
  <PolicySection title="Retention and your choices"><p>Content remains until you delete it; trashed items remain recoverable until permanently deleted. Email <SupportLink /> from your registered address to request access, correction, account deletion, or associated data deletion. Records may be retained where required for security, disputes, or law.</p></PolicySection>
  <PolicySection title="Security and updates"><p>We use reasonable technical safeguards, but no online service can guarantee absolute security. Material changes will be posted here with a revised date.</p></PolicySection>
</PolicyPage>; }
